local bit=require("bit")
local Json=require("miuread.json")
local U=require("miuread.util")
local E={}
local crc={}; for n=0,255 do local c=n; for _=1,8 do c=bit.band(c,1)==1 and bit.bxor(0xedb88320,bit.rshift(c,1)) or bit.rshift(c,1) end; crc[n]=c end
local function crc32(s) local c=0xffffffff; for i=1,#s do c=bit.bxor(bit.rshift(c,8),crc[bit.band(bit.bxor(c,s:byte(i)),255)]) end return bit.bxor(c,0xffffffff) end
local function u16(n) return string.char(n%256,math.floor(n/256)%256) end
local function u32(n) return string.char(n%256,math.floor(n/256)%256,math.floor(n/65536)%256,math.floor(n/16777216)%256) end
local function zip(path,entries)
    local parts,center,off={},{},0
    for _,e in ipairs(entries) do local name,data=e.name,e.data or ""; local sum=crc32(data); local h="PK\003\004"..u16(20)..u16(0)..u16(0)..u16(0)..u16(0)..u32(sum)..u32(#data)..u32(#data)..u16(#name)..u16(0)..name; parts[#parts+1]=h..data; center[#center+1]="PK\001\002"..u16(20)..u16(20)..u16(0)..u16(0)..u16(0)..u16(0)..u32(sum)..u32(#data)..u32(#data)..u16(#name)..u16(0)..u16(0)..u16(0)..u16(0)..u32(0)..u32(off)..name; off=off+#h+#data end
    local c=table.concat(center); local tail="PK\005\006"..u16(0)..u16(0)..u16(#entries)..u16(#entries)..u32(#c)..u32(off)..u16(0); local ok,er=U.atomic_write(path,table.concat(parts)..c..tail,true); if not ok then error(er) end
end
function E.build(path,book,chapters,css,assets,cover,meta)
    local entries={{name="mimetype",data="application/epub+zip"},{name="META-INF/container.xml",data='<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>'}}
    local manifest={'<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>','<item id="css" href="style.css" media-type="text/css"/>','<item id="miu-meta" href="miuread.json" media-type="application/json"/>'}; local spine,nav,ncx={},{},{}; local cover_meta=""
    if cover and cover.data then entries[#entries+1]={name="OEBPS/images/cover"..cover.ext,data=cover.data}; manifest[#manifest+1]='<item id="cover-image" href="images/cover'..cover.ext..'" media-type="'..cover.mime..'" properties="cover-image"/>'; cover_meta='<meta name="cover" content="cover-image"/>' end
    local seen={}; for i,a in ipairs(assets or {}) do if not seen[a.href] then seen[a.href]=true; entries[#entries+1]={name="OEBPS/"..a.href,data=a.data}; manifest[#manifest+1]='<item id="asset'..i..'" href="'..U.xml(a.href)..'" media-type="'..U.xml(a.mime)..'"/>' end end
    for i,ch in ipairs(chapters or {}) do local file=string.format("text/chapter-%04d.xhtml",i); local id="c"..i; local title=ch.title or ("Chapter "..i); local x='<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>'..U.xml(title)..'</title><link rel="stylesheet" href="../style.css" type="text/css"/></head><body data-miuread-book="'..U.xml(book.bookId or book.book_id)..'" data-miuread-chapter="'..U.xml(ch.uid or i)..'">'..tostring(ch.body or "")..'</body></html>'; entries[#entries+1]={name="OEBPS/"..file,data=x}; manifest[#manifest+1]='<item id="'..id..'" href="'..file..'" media-type="application/xhtml+xml"/>'; spine[#spine+1]='<itemref idref="'..id..'"/>'; nav[#nav+1]='<li><a href="'..file..'">'..U.xml(title)..'</a></li>'; ncx[#ncx+1]='<navPoint id="n'..i..'" playOrder="'..i..'"><navLabel><text>'..U.xml(title)..'</text></navLabel><content src="'..file..'"/></navPoint>' end
    local ident="miuread-"..U.id_name(book.bookId or book.book_id); local opf='<?xml version="1.0" encoding="utf-8"?><package xmlns="http://www.idpf.org/2007/opf" unique-identifier="id" version="3.0"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="id">'..ident..'</dc:identifier><dc:title>'..U.xml(book.title or "MiuRead")..'</dc:title><dc:creator>'..U.xml(book.author or "")..'</dc:creator><dc:language>zh-CN</dc:language><dc:source>miuread://book/'..U.xml(book.bookId or book.book_id)..'</dc:source><meta property="dcterms:modified" xmlns:dcterms="http://purl.org/dc/terms/">'..os.date("!%Y-%m-%dT%H:%M:%SZ")..'</meta>'..cover_meta..'</metadata><manifest>'..table.concat(manifest)..'<item id="toc" href="toc.ncx" media-type="application/x-dtbncx+xml"/></manifest><spine toc="toc">'..table.concat(spine)..'</spine></package>'
    entries[#entries+1]={name="OEBPS/package.opf",data=opf}; entries[#entries+1]={name="OEBPS/nav.xhtml",data='<?xml version="1.0"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>目录</title></head><body><nav epub:type="toc"><ol>'..table.concat(nav)..'</ol></nav></body></html>'}; entries[#entries+1]={name="OEBPS/toc.ncx",data='<?xml version="1.0"?><ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1"><head><meta name="dtb:uid" content="'..ident..'"/></head><docTitle><text>'..U.xml(book.title or "MiuRead")..'</text></docTitle><navMap>'..table.concat(ncx)..'</navMap></ncx>'}
    entries[#entries+1]={name="OEBPS/style.css",data=css or "body{line-height:1.75;margin:5%;}img{max-width:100%;height:auto;}"}; entries[#entries+1]={name="OEBPS/miuread.json",data=Json.encode(meta or {})}; zip(path,entries); return path
end
return E
