local logger = require("logger")
local Thoughts = require("miuread.thoughts")
local ok_socket, socket = pcall(require, "socket")

local Annotations = {}
Annotations.__index = Annotations

local CSS = [[
.miu-thought-link,
.miu-thought-link:link,
.miu-thought-link:visited,
.miu-thought-link:hover,
.miu-thought-link:active,
a.miu-thought-link {
    color: inherit !important;
    background: none !important;
    border: 0 !important;
    padding-bottom: 0 !important;
    text-decoration-line: underline !important;
    text-decoration-style: dashed !important;
    text-decoration-thickness: 1px !important;
    text-underline-offset: 1px !important;
}
.miu-inline-mark {
    color: inherit !important;
    background: none !important;
    border: 0 !important;
    padding-bottom: 0 !important;
    text-decoration-line: underline !important;
    text-decoration-style: dashed !important;
    text-decoration-thickness: 1px !important;
    text-underline-offset: 1px !important;
}
.miu-thought-link .miu-inline-mark {
    text-decoration: none !important;
    border: 0 !important;
}
/* Compatibility for books generated by dev.10. New books no longer create this node. */
.miu-thought-star {
    font-size: 0 !important;
    line-height: 0 !important;
    margin: 0 !important;
    color: transparent !important;
    text-decoration: none !important;
    border: 0 !important;
}
]]

local function pause(seconds)
    if ok_socket and socket and type(socket.sleep) == "function" then socket.sleep(seconds) end
end

local function call_with_retry(label, fn)
    local last
    for attempt = 1, 3 do
        local ok, value = pcall(fn)
        if ok and type(value) == "table" then return true, value end
        last = ok and (label .. " returned invalid data") or tostring(value)
        if attempt < 3 then
            logger.warn("[MiuRead][Annotations] retry", "label=", label, "attempt=", tostring(attempt), "error=", tostring(last))
            pause(attempt == 1 and 0.6 or 1.4)
        end
    end
    return false, last
end

local function str(v) return v == nil and "" or tostring(v) end
local function range_key(v) return str(v and (v.range or v.markRange or v.bookmarkRange)) end

local function array_from(data, names)
    if type(data) ~= "table" then return {} end
    for _, name in ipairs(names) do if type(data[name]) == "table" then return data[name] end end
    if #data > 0 then return data end
    return {}
end

local function parse_range(value)
    local a, b = str(value):match("^(%d+)%-(%d+)$")
    a, b = tonumber(a), tonumber(b)
    if not a or not b or b <= a then return nil end
    return a, b
end

local function review_texts(group)
    local rows, seen = {}, {}
    for _, page in ipairs(array_from(group, {"pageReviews", "reviews", "updated"})) do
        local r = type(page.review) == "table" and page.review or page
        local content = str(r.content or r.review or r.text)
        local author = type(r.author) == "table" and r.author or {}
        local author_name = str(author.nick or author.name or r.authorName)
        local key = str(r.reviewId or r.id)
        if key == "" then key = content .. "\0" .. author_name end
        if content ~= "" and not seen[key] then
            seen[key] = true
            rows[#rows + 1] = {
                content = content,
                abstract = str(r.abstract or r.contextAbstract or r.markText),
                created = tonumber(r.createTime or r.createdAt or 0) or 0,
                author = author_name,
                likes = tonumber(page.likesCount or r.likesCount or 0) or 0,
                review_id = str(r.reviewId or r.id),
            }
        end
    end
    return rows
end

local function normalize_reviews(data)
    local map, groups, group_count, entry_count = {}, {}, 0, 0
    for _, group in ipairs(array_from(data, {"reviews", "updated"})) do
        local key = range_key(group)
        if key ~= "" then
            local texts = review_texts(group)
            if #texts > 0 then
                if not map[key] then group_count = group_count + 1; map[key] = {} end
                for _, item in ipairs(texts) do map[key][#map[key] + 1] = item end
                entry_count = entry_count + #texts
            end
        end
    end
    for key, texts in pairs(map) do groups[#groups + 1] = {range = key, texts = texts} end
    table.sort(groups, function(a, b) return tostring(a.range) < tostring(b.range) end)
    return map, groups, group_count, entry_count
end

function Annotations:new(api) return setmetatable({api = api}, self) end

function Annotations:fetch_chapter(book_id, uid, progress)
    local result = {book_id=str(book_id),chapter_uid=str(uid),underlines={},review_map={},review_groups={},underline_count=0,thought_count=0,thought_entry_count=0,errors={},underline_request_ok=false}
    progress = progress or function() end
    local ok, data = call_with_retry("underlines", function() return self.api:underlines(book_id, uid) end)
    if not ok then
        local err = str(data)
        result.errors[#result.errors + 1] = err
        logger.warn("[MiuRead][Annotations] underlines failed", "book=", result.book_id, "chapter=", result.chapter_uid, "error=", err)
        return result
    end
    result.underline_request_ok = true
    result.underlines = array_from(data, {"underlines", "updated", "bookmarks"})
    result.underline_count = #result.underlines
    local ranges, seen = {}, {}
    for _, row in ipairs(result.underlines) do
        local key = range_key(row)
        if key ~= "" and not seen[key] then seen[key] = true; ranges[#ranges + 1] = key end
    end
    progress("underlines", result.underline_count, result.underline_count, "")
    if #ranges == 0 then return result end
    local groups = {}
    local batches = self.api:review_batches(ranges, 5)
    for index, batch in ipairs(batches) do
        progress("thoughts", index, #batches, "")
        local good, response = call_with_retry("thoughts batch " .. tostring(index), function()
            return self.api:readreviews(book_id, uid, batch)
        end)
        if good then
            for _, item in ipairs(array_from(response, {"reviews", "updated"})) do groups[#groups + 1] = item end
        else
            local err = str(response)
            result.errors[#result.errors + 1] = "batch " .. index .. ": " .. err
            logger.warn("[MiuRead][Annotations] thoughts batch failed", "book=", result.book_id, "chapter=", result.chapter_uid, "batch=", index, "/", #batches, "error=", err)
        end
    end
    result.review_map, result.review_groups, result.thought_count, result.thought_entry_count = normalize_reviews({reviews=groups})
    logger.info("[MiuRead][Annotations] chapter fetched", "book=", result.book_id, "chapter=", result.chapter_uid,
        "underlines=", result.underline_count, "thought_groups=", result.thought_count,
        "thought_entries=", result.thought_entry_count, "errors=", #result.errors)
    return result
end

local function utf8_len_at(text, i)
    local c = text:byte(i)
    if not c or c < 0x80 then return 1 end
    if c < 0xE0 then return 2 end
    if c < 0xF0 then return 3 end
    return 4
end

local function tokenize(html)
    local tokens, visible = {}, 0
    local i = 1
    while i <= #html do
        if html:sub(i, i) == "<" then
            local j = html:find(">", i + 1, true)
            if not j then tokens[#tokens + 1] = {kind="text", raw=html:sub(i), start=visible}; break end
            tokens[#tokens + 1] = {kind="tag", raw=html:sub(i, j)}
            i = j + 1
        else
            local j = html:find("<", i, true) or (#html + 1)
            local raw = html:sub(i, j - 1)
            local units, p = {}, 1
            while p <= #raw do
                local entity = raw:sub(p):match("^&[#%w]+;")
                if entity then
                    units[#units + 1] = entity; p = p + #entity
                else
                    local n = utf8_len_at(raw, p)
                    units[#units + 1] = raw:sub(p, p + n - 1); p = p + n
                end
            end
            tokens[#tokens + 1] = {kind="text", raw=raw, units=units, start=visible, stop=visible + #units}
            visible = visible + #units
            i = j
        end
    end
    return tokens, visible
end

local function intervals(data, visible_count)
    local out = {}
    for _, row in ipairs(data.underlines or {}) do
        local a, b = parse_range(range_key(row))
        if a then
            a, b = math.max(0, a), math.min(visible_count, b)
            if b > a then out[#out + 1] = {a=a,b=b,key=range_key(row),thought=#(data.review_map[range_key(row)] or {})>0} end
        end
    end
    table.sort(out, function(x,y) if x.a==y.a then return x.b<y.b end return x.a<y.a end)
    local clean, cursor = {}, -1
    for _, it in ipairs(out) do
        if it.a >= cursor then clean[#clean + 1] = it; cursor = it.b end
    end
    return clean
end

local function render_text_token(token, marks, data)
    if not token.units or #token.units == 0 then return token.raw end
    local out, pos = {}, token.start
    local active, active_id_written = nil, false
    local function close_active()
        if not active then return end
        out[#out + 1] = "</span>"
        if active.thought then out[#out + 1] = "</a>" end
        active = nil; active_id_written = false
    end
    for _, unit in ipairs(token.units) do
        local mark
        for _, it in ipairs(marks) do if pos >= it.a and pos < it.b then mark = it; break end end
        if mark ~= active then
            close_active()
            active = mark
            if active then
                if active.thought then
                    local href = Thoughts.href(data.book_id, data.chapter_uid, active.key)
                    out[#out + 1] = '<a class="miu-thought-link" href="' .. href .. '">'
                    active_id_written = true
                end
                local mark_class = Thoughts.mark_class(active.key)
                out[#out + 1] = '<span class="miu-inline-mark ' .. mark_class .. (active.thought and ' miu-has-thought' or '') .. '" data-miu-range="' .. active.key .. '">'
            end
        end
        out[#out + 1] = unit
        pos = pos + 1
        if active and pos >= active.b then
            local finished = active
            close_active()

        end
    end
    close_active()
    return table.concat(out)
end

local function inject(html, data)
    local tokens, visible_count = tokenize(html)
    local marks = intervals(data, visible_count)
    if #marks == 0 then return html end
    local out = {}
    for _, token in ipairs(tokens) do
        if token.kind == "text" then out[#out + 1] = render_text_token(token, marks, data)
        else out[#out + 1] = token.raw end
    end
    return table.concat(out)
end

function Annotations:apply(html, data)
    if not data or data.underline_count == 0 then return html, "", {underlines=0,thoughts=0} end
    return inject(html, data), CSS, {
        underlines=data.underline_count, thoughts=data.thought_count,
        thought_entries=data.thought_entry_count or 0, errors=#(data.errors or {}),
    }
end

return Annotations
